### ISSUE TITLE
The Linux Command Line

### ISSUE THREAD

**Issue by vincentliu99999** [vincentliu104/Learning-Together#18]
[The Linux Command Line](https://www.amazon.com/Linux-Command-Line-Complete-Introduction/dp/1593273894)

預計學習 Part 1, 2, 3, 4

## Part 1 – Introduction.........................................................................1

- [x] 1 – Introduction................................................................................................2

## Part 2 – Learning The Shell..............................................................9

- [x] 2 – What Is The Shell?...................................................................................10
- [x] 3 – Navigation.................................................................................................14
- [x] 4 – Exploring The System.............................................................................20
- [x] 5 – Manipulating Files And Directories........................................................31
- [x] 6 – Working With Commands........................................................................48
- [x] 7 – Redirection................................................................................................59
- [x] 8 – Seeing The World As The Shell Sees It..................................................72
- [x] 9 – Advanced Keyboard Tricks.....................................................................84
- [x] 10 – Permissions............................................................................................93
- [x] 11 – Processes..............................................................................................113

## Part 3 – Configuration And The Environment.............................127

- [x] 12 – The Environment..................................................................................128
- [x] 13 – A Gentle Introduction To vi.................................................................140
- [x] 14 – Customizing The Prompt.....................................................................160

## Part 4 – Common Tasks And Essential Tools.............................169

- [x] 15 – Package Management..........................................................................170
- 16 – Storage Media.......................................................................................180
- [x] 17 – Networking............................................................................................199
- [x] 18 – Searching For Files..............................................................................213
- [x] 19 – Archiving And Backup.........................................................................230
- [x] 20 – Regular Expressions...........................................................................247
- [x] 21 – Text Processing....................................................................................268
- [x] 22 – Formatting Output................................................................................309
- 23 – Printing..................................................................................................330
- 24 – Compiling Programs............................................................................344

## Part 5 – Writing Shell Scripts.......................................................357

- 25 – Writing Your First Script......................................................................358
- 26 – Starting A Project.................................................................................365
- 27 – Top-Down Design.................................................................................376
- 28 – Flow Control: Branching With if.........................................................385
- 29 – Reading Keyboard Input......................................................................401
- 30 – Flow Control: Looping With while / until...........................................412
- 31 – Troubleshooting...................................................................................419
- 32 – Flow Control: Branching With case...................................................432
- 33 – Positional Parameters.........................................................................437
- 34 – Flow Control: Looping With for..........................................................451
- 35 – Strings And Numbers..........................................................................457
- 36 – Arrays....................................................................................................476
- 37 – Exotica...................................................................................................485

**Comment by vincentliu99999** [comment]
有些許內容重複，事後要整理
