### ISSUE TITLE
ES6 For Everyone

### ISSUE THREAD

**Issue by vincentliu99999** [vincentliu104/Learning-Together#53]
- [ ] Module `#1` New Variables — Creation, Updating and Scoping
- [ ] Module `#2` Function Improvements: Arrows and Default Arguments
- [ ] Module `#3` Template Strings
- [ ] Module `#4` Additional String Improvements
- [ ] Module `#5` Destructuring
- [ ] Module `#6` Iterables & Looping
- [ ] Module `#7` An Array of Array Improvements
- [ ] Module `#8` Say Hello to ...Spread and ...Rest
- [ ] Module `#9` Object Literal Upgrades
- [ ] Module `#10` Promises
- [ ] Module `#11` Symbols
- [ ] Module `#12` Code Quality with ESLint
- [ ] Module `#13` JavaScript Modules and Using npm
- [ ] Module `#14` ES6 Tooling
- [ ] Module `#15` Classes
- [ ] Module `#16` Generators
- [ ] Module `#17` Proxies
- [ ] Module `#18` Sets and WeakSets
- [ ] Module `#19` Map and Weak Map
- [ ] Module `#20` Async + Await Flow Control
- [ ] Module `#21` ES7, ES8 + Beyond
